// coming from Const Help to Idetify from which class we are coming to seltected class
const COMING_FROM = {
    STUDENT_SCREEN: 'studentScreen',
    ACTION_TO_MANY: 'actionToMany',
    HOME_SCREEN:'HomeScreen',
    CLASSES_SCREEN:'ClassScreen',
    CLASSES_SCREEN_STUDENT_SCREEN:'ClassScreen_studentScreen',
    STUDENT_ACTION_FIELDS:'StudentActionFields',
    ACTION_FIELDS_SCREEEN:'ActionFieldsScreen',
    STUDENT_ACTIONS:'StudentActions',
    HOME_SHARED_STUDENT:'HomeSharedStudent',
    SPLASH_SCREEN:'SplashScreen',
    SIGNUP_SCREEN:'SignUpScreen',
    LOGIN_SCREEN :'LoginScreen',
    SETTINGS_IMPORT_SCREEN :'SETTINGS_IMPORT_SCREEN',
    SETTINGS_CUSTOMIZE_DETAIL_FIELDS:'Customize Detail Fields',
    SETTINGS_DEFAULT_ACTION_VALUE:'Default Action Value',
    SETTINGS_CUSTOMIZE_ACTION_FIELDS:'Customize Action Value',
    SETTINGS_CUSTOMIZE_TERMENOLOGY:'Customize Terminology',
    SETTINGS_EMAIL_BLAST_SPECIFY_RECIPIENT:'SettingsEmailBlastSpecifyRecipient',
    ALL_STUDENTS_LIST:"AllStudentsList",
    HOME_EMAIL_BLAST:'HomeEmailBlast',
    HOME_RANDOMIZER:'HomeRandomizer',
    EMAIL_BLAST_SPECIFY_RECIPIENT:'EmailBlastSpecifyRecipient',
    INTIALIZATION_DATA:'IntializationData',
    FILTER_OPTION:'filter',
    EXPORT_DATA_STUDENT_DEMOGRAPHICS:'Student demographics',
    EXPORT_DATA_STUDENT_ACTIONS:'ExportDataStudentAction',
    EXPORT_DATA_REPORT_OPTION:'ExportDataReprotOption', 
};
export default COMING_FROM;